export const ALL_CATEGORIES = [
  "Revenue",
  "Payment Processor Payout",
  "Refunds",
  "Transfers",
  "Owner Drawings",
  "Capital Injection",
  "Loans",
  "Software",
  "AI Tools",
  "Cloud Infrastructure",
  "Advertising",
  "Marketing",
  "Sales and Marketing",
  "Sales Commission",
  "Contractors",
  "Payroll",
  "Professional Services",
  "Consultancy",
  "Rent",
  "Travel",
  "Accommodation",
  "Food and Meals",
  "Office Costs",
  "Bank Fees",
  "Credit Card Payment",
  "Credit Card Fees",
  "Interest Charges",
  "Payment Processor Fees",
  "Tax",
  "Inventory",
  "COGS",
  "Shipping and Fulfilment",
  "Subscriptions",
  "Utilities",
  "Insurance",
  "Training and Education",
  "Shopping",
  "Automotive",
  "Financial Services",
  "Family Support",
  "Personal Spending",
  "Ambiguous",
  "Uncategorised Review",
] as const;

export type CategoryType = typeof ALL_CATEGORIES[number];

export const CATEGORY_COLORS: Record<string, string> = {
  Revenue: "var(--success)",
  "Payment Processor Payout": "var(--success)",
  Refunds: "var(--danger)",
  Transfers: "var(--muted-foreground)",
  "Owner Drawings": "var(--warning)",
  "Capital Injection": "var(--success)",
  Loans: "var(--warning)",
  Software: "var(--sky-blue)",
  "AI Tools": "var(--highlight)",
  "Cloud Infrastructure": "var(--sky-blue)",
  Advertising: "var(--danger)",
  Marketing: "var(--danger)",
  "Sales and Marketing": "var(--danger)",
  "Sales Commission": "var(--danger)",
  Contractors: "var(--neon-cyan)",
  Payroll: "var(--warning)",
  "Professional Services": "var(--neon-cyan)",
  Consultancy: "var(--neon-cyan)",
  Rent: "var(--sky-blue)",
  Travel: "var(--accent)",
  Accommodation: "var(--accent)",
  "Food and Meals": "var(--accent)",
  "Office Costs": "var(--sky-blue)",
  "Bank Fees": "var(--muted-foreground)",
  "Credit Card Payment": "var(--muted-foreground)",
  "Credit Card Fees": "var(--muted-foreground)",
  "Interest Charges": "var(--muted-foreground)",
  "Payment Processor Fees": "var(--danger)",
  Tax: "var(--highlight)",
  Inventory: "var(--soft-lilac)",
  COGS: "var(--soft-lilac)",
  "Shipping and Fulfilment": "var(--accent)",
  Subscriptions: "var(--soft-lilac)",
  Utilities: "var(--sky-blue)",
  Insurance: "var(--soft-lilac)",
  "Training and Education": "var(--soft-lilac)",
  Shopping: "var(--accent)",
  Automotive: "var(--accent)",
  "Financial Services": "var(--muted-foreground)",
  "Family Support": "var(--warning)",
  "Personal Spending": "var(--muted-foreground)",
  Ambiguous: "var(--warning)",
  "Uncategorised Review": "var(--muted-foreground)",
};

export const CATEGORY_SUBCATEGORIES: Record<string, string[]> = {
  Revenue: ["Sales", "Services", "Subscriptions", "Marketplace", "Processor Payout"],
  "Payment Processor Payout": ["Stripe", "PayPal", "Square", "GoCardless", "Marketplace"],
  Software: ["SaaS", "Dev Tools", "CRM", "Accounting", "Design Tool", "Marketing Automation"],
  "Cloud Infrastructure": ["Hosting", "Storage", "CDN", "Compute"],
  Advertising: ["PPC", "Social Media", "Display", "Influencer"],
  Marketing: ["Email Marketing", "SEO", "Content", "Marketing Automation"],
  "Sales and Marketing": ["Commission", "Affiliate", "Sales", "Campaigns"],
  "Sales Commission": ["Affiliate", "Sales Rep", "Referral", "Partner"],
  "Professional Services": ["Legal", "Accounting", "Consulting", "Advisory"],
  Consultancy: ["Director Fee", "Consultant", "Advisory"],
  Travel: ["Flights", "Ground Transport", "Parking"],
  Inventory: ["Stock", "Raw Materials", "Supplies"],
  COGS: ["Supplier", "Materials", "Direct Costs"],
};

export function getCategoryColor(category: string): string {
  return CATEGORY_COLORS[category] || "var(--muted-foreground)";
}

export function getCategoryDisplayName(category: string): string {
  return category;
}

export function isValidCategory(category: string): boolean {
  return ALL_CATEGORIES.includes(category as CategoryType);
}
