import type { ProviderAdapter } from "../adapter-types";

export const monzoAdapter: ProviderAdapter = {
  id: "monzo",
  displayName: "Monzo",
  type: "bank",
  detection: {
    requiredHeaders: ["Date", "Name", "Category", "Amount"],
    optionalHeaders: [
      "Currency",
      "Local amount",
      "Local currency",
      "Notes and tags",
      "Address",
      "Receipt",
      "Description",
      "Category split",
      "Tags",
      "Round up",
      "Change",
    ],
    minRequiredMatches: 2,
    minScore: 30,
    preamblePatterns: ["Notes and tags", "Local amount", "Local currency", "Category split", "Round up"],
  },
  headerAliases: [
    { field: "transactionDate", aliases: ["Date", "date", "Transaction Date", "transaction_date", "created"], required: true },
    { field: "merchantName", aliases: ["Name", "name", "merchant", "counter party", "counterparty", "counter_party"], required: true },
    { field: "description", aliases: ["Description", "description", "Notes and tags", "notes_and_tags", "notes and tags", "memo", "narrative"] },
    { field: "reference", aliases: ["Reference", "reference", "ref", "payment reference", "payment_reference"] },
    { field: "transactionType", aliases: ["Type", "type", "transaction type", "transaction_type", "Category", "category", "category split", "category_split"] },
    { field: "amount", aliases: ["Amount", "amount", "transaction amount", "value"], required: true },
    { field: "currency", aliases: ["Currency", "currency", "ccy", "curr", "currency code"] },
    { field: "originalAmount", aliases: ["Local amount", "local amount", "local_amount", "original amount", "orig amount"] },
    { field: "originalCurrency", aliases: ["Local currency", "local currency", "local_currency", "original currency", "orig currency"] },
    { field: "category", aliases: ["Category", "category", "spending category", "spending_category", "Tags", "tags"] },
  ],
  signConvention: "uk_bank",
  feeHandling: "included_in_amount",
  hasSplitAmountColumns: false,
  knownTransactionTypes: {
    "monzo-to-monzo": { direction: "transfer" },
    pots: { direction: "transfer" },
    refund: { direction: "income" },
    interest: { direction: "income" },
  },
  transferPatterns: ["pot transfer", "monzo to monzo", "flex", "split the"],
  dateFormatHints: ["DD/MM/YYYY"],
  detectionWeight: 1.0,
};
