import type { ProviderAdapter } from "../adapter-types";

export const paypalAdapter: ProviderAdapter = {
  id: "paypal_csv",
  displayName: "PayPal",
  type: "payment_processor",
  detection: {
    requiredHeaders: ["Date", "Name", "Type", "Gross", "Currency"],
    optionalHeaders: [
      "Time",
      "TimeZone",
      "Status",
      "Fee",
      "Net",
      "From Email Address",
      "To Email Address",
      "Transaction ID",
      "Reference Transaction ID",
      "Invoice Number",
      "Subject",
      "Note",
      "Bank Name",
      "Bank Account",
      "Shipping and Handling Amount",
      "Sales Tax",
      "Credit Applied",
      "Balance Impact",
    ],
    minRequiredMatches: 3,
    minScore: 40,
  },
  headerAliases: [
    { field: "transactionDate", aliases: ["Date"], required: true },
    { field: "description", aliases: ["Subject", "Note", "Name"], required: true },
    { field: "amount", aliases: ["Gross"], required: true },
    { field: "feeAmount", aliases: ["Fee"] },
    { field: "currency", aliases: ["Currency"] },
    { field: "status", aliases: ["Status"] },
    { field: "externalTransactionId", aliases: ["Transaction ID"] },
    { field: "transactionType", aliases: ["Type"] },
    { field: "merchantName", aliases: ["Name", "From Email Address"] },
    { field: "counterpartyName", aliases: ["To Email Address", "From Email Address"] },
    { field: "reference", aliases: ["Invoice Number", "Reference Transaction ID"] },
    { field: "originalAmount", aliases: ["Net"] },
  ],
  signConvention: "accounting",
  feeHandling: "separate_column",
  hasSplitAmountColumns: false,
  knownTransactionTypes: {
    "Payment Received": { direction: "income", category: "Sales" },
    "Payment Sent": { direction: "expense" },
    Refund: { direction: "expense", category: "Refunds" },
    Transfer: { direction: "transfer" },
    Withdrawal: { direction: "transfer" },
    Deposit: { direction: "transfer" },
    "Currency Conversion": { direction: "neutral" },
    "Fee": { direction: "fee", category: "Payment Processing Fees" },
  },
  transferPatterns: ["Transfer", "Payout", "Withdrawal", "Deposit", "Balance Impact"],
  dateFormatHints: ["DD/MM/YYYY", "MM/DD/YYYY"],
  detectionWeight: 1.0,
};
