import type { ProviderAdapter } from "../adapter-types";

export const revolutAdapter: ProviderAdapter = {
  id: "revolut_business_csv",
  displayName: "Revolut Business",
  type: "bank",
  detection: {
    requiredHeaders: [
      "Date Completed",
      "Date Started",
      "Related Transaction ID",
      "Type",
      "State",
    ],
    optionalHeaders: [
      "ID",
      "Description",
      "Reference",
      "Fee",
      "Total Amount",
      "Account",
      "MCC",
      "Orig Currency",
      "Orig Amount",
      "Payment Currency",
      "Amount",
      "Balance",
      "Payer",
      "Beneficiary account number",
    ],
    minRequiredMatches: 3,
    minScore: 50,
  },
  headerAliases: [
    { field: "transactionDate", aliases: ["Date Completed", "Date Completed UTC", "Completed Date", "Date Completed (UTC)"], required: true },
    { field: "postedDate", aliases: ["Date Started", "Date Started UTC", "Started Date", "Date Started (UTC)"] },
    { field: "externalTransactionId", aliases: ["ID", "Transaction ID"] },
    { field: "description", aliases: ["Description", "Details", "Narrative"], required: true },
    { field: "reference", aliases: ["Reference", "Ref", "Payment Reference"] },
    { field: "transactionType", aliases: ["Type", "Transaction Type"] },
    { field: "status", aliases: ["State", "Status"] },
    { field: "amount", aliases: ["Amount"], required: true },
    { field: "debitAmount", aliases: [] },
    { field: "creditAmount", aliases: [] },
    { field: "currency", aliases: ["Payment Currency", "Currency"] },
    { field: "originalCurrency", aliases: ["Orig Currency", "Original Currency", "Orig. Currency"] },
    { field: "originalAmount", aliases: ["Orig Amount", "Original Amount", "Orig. Amount"] },
    { field: "exchangeRate", aliases: ["Exchange Rate", "Exchange rate", "Rate"] },
    { field: "feeAmount", aliases: ["Fee", "Transaction Fee"] },
    { field: "feeCurrency", aliases: ["Fee Currency", "Fee currency"] },
    { field: "runningBalance", aliases: ["Balance", "Running Balance", "Account Balance"] },
    { field: "accountName", aliases: ["Account", "Account Name"] },
    { field: "merchantCategoryCode", aliases: ["MCC", "Merchant Category Code"] },
    { field: "counterpartyName", aliases: ["Payer"] },
    { field: "merchantName", aliases: ["Description", "Details", "Narrative"] }
  ],
  signConvention: "uk_bank",
  feeHandling: "separate_column",
  hasSplitAmountColumns: false,
  knownTransactionTypes: {
    CARD_PAYMENT: { direction: "expense", category: "Card Payment" },
    // Revolut uses TRANSFER for both internal movements and ordinary bank
    // payments. Treat the raw type as neutral; downstream rules require
    // stronger evidence before excluding the row from KPIs.
    TRANSFER: { direction: "neutral" },
    TOPUP: { direction: "income" },
    FEE: { direction: "fee", category: "Bank Fees" },
    REFUND: { direction: "income", category: "Refunds" },
    EXCHANGE: { direction: "neutral" },
  },
  transferPatterns: ["TRANSFER", "Exchange", "From British Pound", "To British Pound", "Business Savings"],
  dateFormatHints: ["YYYY-MM-DDTHH:mm:ssZ"],
  detectionWeight: 1.1,
};
