import type { ProviderAdapter } from "../adapter-types";

export const squareAdapter: ProviderAdapter = {
  id: "square_csv",
  displayName: "Square",
  type: "payment_processor",
  detection: {
    requiredHeaders: ["Date", "Gross Sales", "Net Total", "Fees"],
    optionalHeaders: [
      "Time",
      "Discounts",
      "Net Sales",
      "Tax",
      "Tip",
      "Total Collected",
      "Card",
      "Cash",
      "Other",
      "Payment ID",
      "Device Name",
      "Details",
      "Description",
      "Event Type",
      "Location",
    ],
    minRequiredMatches: 3,
    minScore: 40,
  },
  headerAliases: [
    { field: "transactionDate", aliases: ["Date"], required: true },
    { field: "description", aliases: ["Details", "Description", "Event Type"], required: true },
    { field: "amount", aliases: ["Gross Sales", "Total Collected"], required: true },
    { field: "feeAmount", aliases: ["Fees"] },
    { field: "externalTransactionId", aliases: ["Payment ID"] },
    { field: "transactionType", aliases: ["Event Type"] },
    { field: "merchantName", aliases: ["Location", "Device Name"] },
    { field: "originalAmount", aliases: ["Net Total", "Net Sales"] },
  ],
  signConvention: "accounting",
  feeHandling: "separate_column",
  hasSplitAmountColumns: false,
  fixedCurrency: "GBP",
  knownTransactionTypes: {
    "Payment": { direction: "income", category: "Sales" },
    "Refund": { direction: "expense", category: "Refunds" },
    "Transfer": { direction: "transfer" },
    "Deposit": { direction: "transfer" },
    "Fee": { direction: "fee", category: "Payment Processing Fees" },
  },
  transferPatterns: ["Transfer", "Payout", "Withdrawal", "Deposit"],
  dateFormatHints: ["MM/DD/YYYY", "DD/MM/YYYY"],
  detectionWeight: 1.0,
};
