import type { ProviderAdapter } from "../adapter-types";

export const stripeAdapter: ProviderAdapter = {
  id: "stripe_csv",
  displayName: "Stripe",
  type: "payment_processor",
  detection: {
    requiredHeaders: ["id", "Amount", "Currency", "Created"],
    optionalHeaders: [
      "Description",
      "Fee",
      "Net",
      "Available On (UTC)",
      "Status",
      "Report Type",
      "Card Brand",
      "Card Funding",
      "Card Country",
      "Statement Descriptor",
      "Dispute Reason",
      "Refund Reason",
      "Conversion Rate",
      "Customer ID",
      "Customer Description",
      "Customer Email",
      "Capture",
      "Card ID",
      "Invoice ID",
      "Transfer",
      "Transfer Group",
    ],
    minRequiredMatches: 3,
    minScore: 40,
  },
  headerAliases: [
    { field: "transactionDate", aliases: ["Created (UTC)", "Created", "Date"], required: true },
    { field: "description", aliases: ["Description"], required: true },
    { field: "amount", aliases: ["Amount"], required: true },
    { field: "feeAmount", aliases: ["Fee"] },
    { field: "currency", aliases: ["Currency"] },
    { field: "status", aliases: ["Status"] },
    { field: "externalTransactionId", aliases: ["id", "ID"] },
    { field: "transactionType", aliases: ["Report Type", "Type"] },
    { field: "merchantName", aliases: ["Statement Descriptor", "Customer Description"] },
    { field: "reference", aliases: ["Invoice ID", "Transfer", "Transfer Group"] },
    { field: "accountName", aliases: ["Card Brand", "Card Funding", "Card Country"] },
    { field: "originalCurrency", aliases: ["Currency"] },
    { field: "originalAmount", aliases: ["Net"] },
    { field: "counterpartyName", aliases: ["Customer Description", "Customer Email"] },
  ],
  signConvention: "accounting",
  feeHandling: "separate_column",
  hasSplitAmountColumns: false,
  knownTransactionTypes: {
    charge: { direction: "income", category: "Sales" },
    payment: { direction: "income", category: "Sales" },
    refund: { direction: "expense", category: "Refunds" },
    dispute: { direction: "expense", category: "Disputes" },
    transfer: { direction: "transfer" },
    payout: { direction: "transfer", category: "Payout" },
    adjustment: { direction: "neutral" },
    fee: { direction: "fee", category: "Payment Processing Fees" },
  },
  transferPatterns: ["Transfer", "Payout", "Withdrawal"],
  dateFormatHints: ["MM/DD/YYYY HH:mm:ss", "YYYY-MM-DD HH:mm:ss"],
  detectionWeight: 1.0,
};
